ac_btree: Re-work ac_btree_foreach() (again...)
Commit 9c97a4d ("ac_btree: Adjust the ac_btree_foreach() interface")
unfortunately broke compilation under glibc < 2.30.

ac_btree.c: In function 'ac_btree_foreach':
ac_btree.c:73:2: warning: implicit declaration of function 'twalk_r' [-Wimplicit-function-declaration]
  twalk_r(tree->rootp, action, user_data);
  ^

That was under CentOS 7 with glibc 2.17.

I had missed the fact that the twalk_r(3) function was only introduced
in glibc 2.30 (2019-08-01).

However, instead of simply reverting the above commit, I've put back the
original version of ac_btree_foreach() and renamed the new version that
uses twalk_r() to ac_btree_foreach_data() and guarded it by a glibc
version check.

Fixes: 9c97a4d ("ac_btree: Adjust the ac_btree_foreach() interface")
Signed-off-by: Andrew Clayton <andrew@digital-domain.net>